<?php

/**
 * This is the model base class for the table "job".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Job".
 *
 * Columns in table "job" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $job_class
 * @property string $job_data
 * @property string $crontab
 * @property string $planned_time
 * @property string $start_time
 * @property integer $job_status_id
 * @property string $create_time
 * @property string $update_time
 *
 */
abstract class BaseJob extends CActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'job';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Job|Jobs', $n);
	}

	public static function representingColumn() {
		return 'job_class';
	}

	public function rules() {
		return array(
			array('job_class, planned_time, job_status_id', 'required'),
			array('job_status_id', 'numerical', 'integerOnly'=>true),
			array('job_class', 'length', 'max'=>64),
			array('crontab', 'length', 'max'=>128),
			array('job_data, start_time, create_time, update_time', 'safe'),
			array('job_data, crontab, start_time, create_time, update_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, job_class, job_data, crontab, planned_time, start_time, job_status_id, create_time, update_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'job_class' => Yii::t('app', 'Job Class'),
			'job_data' => Yii::t('app', 'Job Data'),
			'crontab' => Yii::t('app', 'Crontab'),
			'planned_time' => Yii::t('app', 'Planned Time'),
			'start_time' => Yii::t('app', 'Start Time'),
			'job_status_id' => Yii::t('app', 'Job Status'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('job_class', $this->job_class, true);
		$criteria->compare('job_data', $this->job_data, true);
		$criteria->compare('crontab', $this->crontab, true);
		$criteria->compare('planned_time', $this->planned_time, true);
		$criteria->compare('start_time', $this->start_time, true);
		$criteria->compare('job_status_id', $this->job_status_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}