<?php

/**
 * This is the model base class for the table "job_log".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "JobLog".
 *
 * Columns in table "job_log" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $job_class
 * @property string $start_time
 * @property string $finish_time
 * @property integer $job_status_id
 * @property string $finish_message
 * @property string $create_time
 * @property string $update_time
 * @property string $queue
 * @property integer $progress
 * @property string $job_data
 * @property integer $job_id
 * @property string $token
 * @property string $identifier1
 * @property string $identifier2
 * @property string $identifier3
 * @property string $identifier4
 *
 */
abstract class BaseJobLog extends TgActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'job_log';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'JobLog|JobLogs', $n);
    }

    public static function representingColumn() {
        return 'job_class';
    }

    public function rules() {
        return array(
            array('job_class, start_time, finish_time, job_status_id', 'required'),
            array('job_status_id, progress, job_id', 'numerical', 'integerOnly'=>true),
            array('job_class, identifier1, identifier2, identifier3, identifier4', 'length', 'max'=>64),
            array('queue', 'length', 'max'=>45),
            array('token', 'length', 'max'=>23),
            array('finish_message, create_time, update_time, job_data', 'safe'),
            array('finish_message, create_time, update_time, queue, progress, job_data, job_id, token, identifier1, identifier2, identifier3, identifier4', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, job_class, start_time, finish_time, job_status_id, finish_message, create_time, update_time, queue, progress, job_data, job_id, token, identifier1, identifier2, identifier3, identifier4', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id' => Yii::t('app', 'ID'),
            'job_class' => Yii::t('app', 'Job Class'),
            'start_time' => Yii::t('app', 'Start Time'),
            'finish_time' => Yii::t('app', 'Finish Time'),
            'job_status_id' => Yii::t('app', 'Job Status'),
            'finish_message' => Yii::t('app', 'Finish Message'),
            'create_time' => Yii::t('app', 'Create Time'),
            'update_time' => Yii::t('app', 'Update Time'),
            'queue' => Yii::t('app', 'Queue'),
            'progress' => Yii::t('app', 'Progress'),
            'job_data' => Yii::t('app', 'Job Data'),
            'job_id' => Yii::t('app', 'Job'),
            'token' => Yii::t('app', 'Token'),
            'identifier1' => Yii::t('app', 'Identifier1'),
            'identifier2' => Yii::t('app', 'Identifier2'),
            'identifier3' => Yii::t('app', 'Identifier3'),
            'identifier4' => Yii::t('app', 'Identifier4'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('job_class', $this->job_class, true);
        $criteria->compare('start_time', $this->start_time, true);
        $criteria->compare('finish_time', $this->finish_time, true);
        $criteria->compare('job_status_id', $this->job_status_id);
        $criteria->compare('finish_message', $this->finish_message, true);
        $criteria->compare('create_time', $this->create_time, true);
        $criteria->compare('update_time', $this->update_time, true);
        $criteria->compare('queue', $this->queue, true);
        $criteria->compare('progress', $this->progress);
        $criteria->compare('job_data', $this->job_data, true);
        $criteria->compare('job_id', $this->job_id);
        $criteria->compare('token', $this->token, true);
        $criteria->compare('identifier1', $this->identifier1, true);
        $criteria->compare('identifier2', $this->identifier2, true);
        $criteria->compare('identifier3', $this->identifier3, true);
        $criteria->compare('identifier4', $this->identifier4, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}